Feature/ add Case Study page
nkeumosoft/ninjashpere pull request #9
Opened 2022-10-03 12:32 UTC by yvanclement

2022-10-03 12:53 UTC, yvanclement commented
![Screenshot 2022-10-03 at 13-37-18 NinjaSphere](https://user-images.githubusercontent.com/104658441/193581300-cc54fd0a-67d1-4e91-bdac-988ab2a42082.png)
![Screenshot 2022-10-03 at 13-41-08 NinjaSphere](https://user-images.githubusercontent.com/104658441/193581353-97b6d503-d176-41b8-837e-f54ad7629e43.png)

2022-10-03 17:08 UTC, tchassijordan requested changes
Pour un theme générale je peut dire qu'il faut que tu améliore les nome des classe que tu utilise. Choisir les nom descriptif. 
Également change les noms de tes images. Utilise les nom descriptif, arrête d’utiliser les noms comme vector2, vector3 meme si c'est le nom qui est venu avec les fiche quand tu là télécharger

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +    <section class="footer">
En HTML5 il y a la balise `<footer></footer>`. Utilise cela en place du `<section>`. Tu peut garde la class _**footer**_ mais pour ecrice du bon code semantic(HTML5) il faut utilise le footer quand tu veut créer le footer.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        <div class="menu">
Les `<li></li>` sont sensés être les enfants directe d'uns liste. Soit une list ordonnée(`<ol>`) ou une list non ordonnée(`<ul>`). 
Si on l'utilise c'est dans une liste, donc il faut change ton implementation

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        href="https://fonts.googleapis.com/css2?family=Barlow:wght@600&family=Fraunces:opsz,wght@9..144,700;9..144,900&display=swap"
Pourquoi tu import la police Barlow?? 
Cette police n'est pas utilise dans le project donc ne l'import pas. Les seule police qui devront être import/télécharge sont **Source sans pro**, **Poppins**, **Lexend**. 

Quand tu import les police ou des resource qui ne sont pas utilise dans ton project tu faire l'utilisateur gaspille les MBs(data) pour rien pour télécharge ses resources, ça rends également le temp de chargement de ton site lente pour rien.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        href="https://fonts.googleapis.com/css2?family=Barlow:wght@600&family=Fraunces:opsz,wght@9..144,700;9..144,900&display=swap"
Tu a import la police barlow et fraunce 5 a 6 foire alors que ce n'est pas utilise dans le project. 
Il faut en lever tous ses import, et tu mets juste les liens pour les police utilise dans le project(site web) ctd **Source sans pro**, **Poppins**, **lexend**

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +    <div class="navbar">
Il faut utilise du HTML5(HTML semantic). Dans le HTML5 il y a la balaise `<nav>` qui est utilise pour la créer la bar de navigation. 
Tu peut preserve la class navbar, mais il faut a tout prix utilise du HTML semantic(HTML5)

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        <li><a href="#">PRESENTATION</a></li>
Les `<li></li>` sont sensés être les enfants directe d'uns liste. Soit une list ordonnée(`<ol>`) ou une list non ordonnée(`<ul>`). 
Si on l'utilise c'est dans une liste, donc il faut change ton implementation

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        <a class="get" href="">Get in touch</a>
Il faut cherche un nome plus convenant pour cette classe. `get` n'est pas bon. 
Tu peut n'est pas oblige d’utilisé les nomme Anglais. 

C'est mieux d’utilisé un nom comme _contact-button_, _get-in-touch-btn_, etc. Il faut que le nomme a prevu dit se que ça fait ou quelle element elle est entrain de stylé

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        <img src="../../static/websitecore/img/case-study-images/Vector.png" alt="vector">
Le `alt` d'une image est sense donnée un peut d'information descriptif, le alt doit parle de l'image ou de sont role dans le site. On n'écrire pas le `alt` aléatoirement parce que on veut affiche une image, on choisir le alt qui donne avec l'image et son role. 

Le **alt** est généralement affiche par le navigateur quand il ne peut pas trouve ta photo ou image. 

Dans ton cas si on prend l’hypothèse qui le navigateur na pas réussi a trouve ton image(`../../static/websitecore/img/case-study-images/Vector.png`), le texte qui sera affiche sera `vector`. L'utilisateur en voyant ça, il vas se posse tellement des questions comme; que signifie vector?? qu'est ce que vector est sensé faire?? Je faire quoi avec vector?? et ça ce n'est pas bon. 

Il faut egalement change les nom de tes image, Je faire que tu a telecharge ces image de figma et c'est ils sont venus avec les noms que je voir comme istockphoto-...., Vector.png, dev2.png, etc 
Mais ses nom ne sont pas bon, il faut change tout les nome pour que ça reflect ce qui est sur l'image ou le role de l'image ou le vecteur(svg). 

Un example très simple 👇🏾 
Si l'image en question est une icon(disons l'icon de research 🔍 ), que de preserve le nom **_vector.svg_** qui est venu avec quand tu là téléchargé, tu le renom a **_search-bar-icon.svg_**. 
Là quelqu'un d'autre en travaillant sur ton projet il sais que le svg si c'est pour l’icône de recherche

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +            <center>Case Studies</center>
Une autre alternatif que je te conseil d’utilisé pour les positionner un element au milieu de son parent(conteneur) est d’utiliser les margins. 

Voici quel que resource qui peuvent t'aide a le faire 
- https://stackoverflow.com/questions/356809/best-way-to-center-a-div-on-a-page-vertically-and-horizontally
- https://www.w3schools.com/css/css_align.asp

Pour le faire il suffit de pour l’élément en question un `margin: auto`
Positionne au centre et horizontalement: `margin-left: auto;` `margin-right: auto`

Crée un nouvelle classe pour ça et tu donnée tous ces éléments cette nouvelle classe

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        <div class="case4">
la classe `case4` ou `case3` sont pas des si mauvais nom. Mais un probleme qui peut se posse quand tu auras beaucoup "case" est qu'il vas falloir tous le nomme différemment. 

Si tu a 100 case par exemple, tu vas continue a les nomme come suite; case1, case2, case3, case4, ...., case100. 
Puis il vas falloir les traite tous différemment dans ton CSS vu qu'il n’ont pas le meme nom.  

Tu voir que ça c'est trop de travail pour rien. Il faut donne tous les case la meme classe. 
Quand je voir ton code il y a pas de difference coté style entre ses éléments

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +                quaerat aliquid id animi. <br>
Évite un peut d'utiliser les `<br>` pour mettre de l'espace entre deux élément ou du texte 

Utilise plus le margin et le padding pour mettre l'espace entre deux éléments.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +            <strong>
`<strong>`sont utilise pour donne plus d'importance a un texte. 
La tu l'utilise pour ajoute le font-weight. 

Utilise plus tot le CSS pour faire cela. 

En plus le text si est sensé être un titre, pas un paragraph.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +            <p class="pform2">The team will usually respond within 1 hour.</p> <br>
Utilise un nome mieux que ça. 

Qu'est ce que pform2 veut dire???

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +            <label for="name" aria-placeholder="yvan">name</label>
J'aime le fait que tu a essayé d'utiliser le aria-placeholder. On utilise les attribues comme ceci pour améliorer l’accessibilité. j'aime ce progrès 🔥 🔥 

Par contre tu la pas utilise sur le bon élément. On le met généralement sur les élément ou on saisir du texte ou on entre les donne(comme `<input>`, `<textarea>`). 

Voici quelque resources pour t’explique l’utilité des aria labels. 
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-placeholder
- https://stackoverflow.com/questions/70686564/what-is-the-difference-between-placeholder-and-aria-placeholder-in-html5

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +    <div class="allcases">
Utiliser du HTML5(HTML semantic). 
Utilise une section ici.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
J'ai regarde dans ton fiche tu n'a pas utilise les icons de font awesome, donc il faut en lever le `<link>` tag si. 

Si tu utilise les icon de font awesome tu peut le laisse.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
Il faut en lever ça. Le favicon est utilise pour mettre l'icone de le site web. 

Dans cette article tu peut voir pourquoi on utilise des favicon https://www.alsacreations.com/astuce/lire/59-icon-link-rel-favicon-ico-navigateur.html 

Mais dans ton cas ce n'est pas nécessaire de le faire.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +    font-family: poppins;
Il faut en lever ça. 
Quand tu met les propriété css dans `* {}` ça s’applique a tous les éléments de ton site web. 

Utilise la police poppins seulement pour les sous-titre. 
- Utilise Lexend pour les titre principaux
- Utilise source sans pro pour les text descriptif ou les text sans importance.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +    font-weight: bolder;
Utilise plutot les chiffre comme font-weight. 
Dans le cas si bolder => 800

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +    font-size: 16px;
Le font-size par défaut c'est 16px; Donc tu n'a pas besoin de le mettre.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +}
les classes case1, case2, case3, case4 ont tous le meme style. Utilise une seule classe pour cela. 
Tu peut utilise une seule classe et tu utilise le pseudo-class(`:last-child`) pour mettre les style uniquement a le dernier element avec la classe **case**

Également cherche un nom mieux que ce `case`. Utilise quelque chose comme `case-study-item`

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +.foot {
Cherche un mot mieux que ça. 
C'est ne pas assez explicatif.

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +.spa {
La classe si style quelle element ?? 
Qu'est ce que spa veut dire???
Cherche un mot mieux que ça, un mot qu'est explicatif

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +.par {
La classe si style quelle element ?? 
Qu'est ce que `par` veut dire???
Cherche un mot mieux que ça, un mot qu'est explicatif

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +@media  (max-width:500px ) {
Ton responsive n'est pas beau. 
Il faut l’améliorer. 

Le faut modifie le font-size, padding, margin, line-height, ... etc pour rendre le site beau sur telephone. 
Change juste le flex-direction ne suffit pas. Il faut faire mieux. 

Quand ont faire le responsive on ouvre généralement la page web en mode telephone pour voir le résultat. En fonction de ça on améliore nos style. 

Voici un article qui explique comment ouvrir ton site en mode telephone sur ta machine 
- https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +.formulaire {
Merci, voici un exemple d'un très bon nom pour une classe 🔥 🔥

2022-10-03 17:08 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +.pform {
Par contre le nom si(`pform`) n'est pas assez descriptif. 
Il faut qu'on réussi a savoir l'élément qu'une classe style sans trop regarde ton fiche HTML. 

On écrire du code pour les humanes et non pour l'ordinateur. Si on écrivais le code pour l'ordinateur on devais écrire du les code comme ça. Vu que l'ordinateur comprends que les `1` et les `0` 
Avant de choisir un nom pour une classe essaye de lit le nom que tu a choisir comme si ce n'est pas toi l'autour du code. Faire ça et tu essaye de voir si le nom la a un sense.

2022-10-03 17:31 UTC, yvanclement commented on website/websitecore/static/websitecore/css/case-study.css
> +    font-size: 16px;
ok

2022-10-04 13:30 UTC, yvanclement commented on website/websitecore/templates/websitecore/case-study.html
> +    <section class="footer">
footer => navbarend

2022-10-04 13:33 UTC, yvanclement commented on website/websitecore/templates/websitecore/case-study.html
> +        <div class="menu">
Modifiée en unorderlist

2022-10-04 15:10 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +    <section class="footer">
Le probleme n'est pas le nome de la classe que tu utilise. Le probleme est que tu a utilisé la balise <section> au lieu de <footer></footer>. 

Je pense que la façon donc tu a nomme ta classe ici(**footer**) est très bon. Il faut juste change le `section` en `footer`
Voici un article de w3school qui explique en détaille l'utilité du [footer](https://www.w3schools.com/tags/tag_footer.asp)

2022-10-20 19:31 UTC, tchassijordan requested changes

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +flex-wrap: wrap;
Prochainement, il faut mettre flex-wrap seulement sur les conteneur flex. 
Quand tu le mets comme ça, la propriéte **flex-wrap** vas etre applique sur tous les elements du document, meme les element qui n'ont pas besion de ça(les elements qui ne sont pas les conteneur flex)

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        </div>
Ici tu ferme le `<div>` deux fois alors que tu a seulement un seule div

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +            <h3 class="title">Case 1</h3>
Ici est un bon endroit pour utilise le `<section>`. 
Le section est généralement utilise pour regroupe les segment du document. 

Donc ce qu'il fallait faire c'est de regouper chaque titre est sont text/img dans une section 👇🏾 
```html 
<section>
   <h1>Case 1</h1>
   <div>......image et text....</div>
</section>
```
ou meme mieux
```html 
<section>
   <h1>Case 1</h1>
   <section>
       <div>image</div>
       <section>
          <h1>Sous-titre</h1>
          <p>....text description....</p>
       </section
   </section>
</section>
```

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +                <p class="firstp">Contact the team today for advice on your digital marketing campaign</p>
Ici c'est mieux d'utilise un titre. h1, h2, h3, ..... h6, hgroup
le `hgroup` est utilise dans les circumstance comme celle si ou il y a beaucoup plus titre(titre, sous-titre)

Donc s'il faut ecrire la version semantic de la partie si ça sera. 
```html
<hgroup>
   <h1>Contact ....</h1>
   <h2>If you .....</h2>
</hgroup>
```
Ça c'est plus semantic.

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +        <section class="navbarend">
Tous cette partie doit etre dans le footer. 
The footer est sensé contenir le contenu qui cloture le document.

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/templates/websitecore/case-study.html
> +                <div class="infos-localisation">
Pour rendre cette partie plus semantic, il faut mettre tous le conteneur qui ce situe dans
```html  
<div class="infos-localisation>......</div>  
```
dans une balise `<address></address>` 
`<address>` est généralement utilise pour affiches les address

Donc ça deviens 
```html  
<address class="infos-localisation>......</address>  
```

2022-10-20 19:31 UTC, tchassijordan commented on website/websitecore/static/websitecore/css/case-study.css
> +.firstp {
Le nom ci c'est pas vraiment explicatif. 
Tu pouvais utiliser quelque chose comme **premier-titre-du-formulaire**
Et pour le deuxième 
Tu pouvais utiliser quelque chose comme **deuxième-titre-du-formulaire**

2022-10-27 10:18 UTC, tchassijordan commented
Reviewed 👍🏾

2022-10-27 10:18 UTC, closed without merging